config/routes.rb
Chmoodme::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "u:user_id" => 'users#show', as: :user_show
  get "users/list"
  get "chmoods/add", :to => 'chmoods#add', :as => :chmoods_add
  post "chmoods/add", :to => 'chmoods#add', :as => :chmoods_add_post

  post "toogle_follow/:user_id", :to => 'users#toggle_follow', :as => :toogle_follow
  post "chmoods/:chmood_id/comments", :to => 'chmoods#comment_add', :as => :chmoods_comment_add

  resource :comments

  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: "home#index"
  get "wannamood/:colour_id", to: "home#index", as: 'wannamood'

  match '*path' => redirect('/'), via: [:get, :post]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!

  MAX_COLOURS = 5

  PAGE_TITLES = {1 => '[Comedy] - have Fun', 2 => 'Be [Inspired]', 3 => '[Discover] new', 4 => '[Create] smth special', 5 => 'Keep [Moments]'}

  def index


    if params[:colour_id].present?

      @colour_id = params[:colour_id].to_i

    else
      @colour_id = 1 # hardcoded
    end

    @next = @colour_id + 1

    if @next > MAX_COLOURS
      @next = 1
    end

    @prev = @colour_id - 1

    if @prev <= 0
      @prev = MAX_COLOURS
    end


    @page_title = PAGE_TITLES[@colour_id]


    @chmoods = Chmood.joins("INNER JOIN users ON chmoods.user_id = users.id INNER JOIN friendships ON users.id = friendships.friend_id").where("friendships.user_id = ?", current_user.id)
    .where('colour_id = ?', @colour_id)
    .order('created_at DESC') #.includes(:user)

    ActiveRecord::Associations::Preloader.new(@chmoods, :user).run # because we will call .user for each chmood



  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-3"></div>

  <div class="col-sm-6 text-center">
    <% if user_signed_in? %>
        <span>Welcome, <%= current_user.email %>!</span> |
        <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
    <% else %>
        <%= link_to 'Sign In', new_user_session_path %> или <%= link_to 'Register', new_user_registration_path %>
    <% end %>
  </div>
  <div class="col-sm-3"></div>

</div>



<div class="row">
  <div class="col-md-12">
    <h1 style="margin-left: 24px"><%= @page_title %></h1>
  </div>
</div>
<div class="row">

  <div class="col-sm-3">
    <div class="colour-page-switcher-container">
      <div class="">
        <%= link_to('<', wannamood_url({:colour_id => @prev, :r => rand(0..1000).to_i }), {:class => 'colour-page-switcher'}) %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div id="main" role="main">
      <ul id="grid" class="grid effect-6">
        <%= render :partial => 'chmoods/chmoods_list', :locals => { :chmoods => @chmoods } %>
      </ul>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="colour-page-switcher-container">
      <div class="">
        <%= link_to('>', wannamood_url({:colour_id => @next }), {:class => 'colour-page-switcher'}) %>
      </div>
    </div>
  </div>
</div>