config/routes.rb
Chmoodme::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "u:user_id" => 'users#show', as: :user_show
  get "users/list"
  get "chmoods/add", :to => 'chmoods#add', :as => :chmoods_add
  post "chmoods/add", :to => 'chmoods#add', :as => :chmoods_add_post

  post "toogle_follow/:user_id", :to => 'users#toggle_follow', :as => :toogle_follow
  post "chmoods/:chmood_id/comments", :to => 'chmoods#comment_add', :as => :chmoods_comment_add

  resource :comments

  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: "home#index"
  get "wannamood/:colour_id", to: "home#index", as: 'wannamood'

  match '*path' => redirect('/'), via: [:get, :post]

end

app/models/chmood.rb
class Chmood < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :user_id, :colour_id, :type_id, :message => "can't be blank"

  validates :content, length: { maximum: 256 }
  validates :content, length: { maximum: 256 }

  default_scope order('created_at DESC')


  has_attached_file :image, styles: {
      thumb: '', #128x128>',
      square: '', #200x200#',
      medium: '' #'300x300>'
  },
  :convert_options => {
      :thumb => Proc.new { |instance| instance.thumnail_dimension(64) },
      :medium => Proc.new { |instance| instance.thumnail_dimension(210) }
  }

  # http://stackoverflow.com/questions/15423330/how-to-make-paperclip-crop-and-not-scale-an-attached-image
  def thumnail_dimension(size=100)
    dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)
    min = dimensions.width > dimensions.height ? dimensions.height : dimensions.width
    "-gravity Center -crop #{min}x#{min}+0+0 +repage -resize #{size}x#{size}^"
  end

  # Validate content type
  validates_attachment_content_type :image, :content_type => /\Aimage/
  # Validate filename
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/]
  # Explicitly do not validate
  # do_not_validate_attachment_file_type :image
  #validates_attachment_presence :image

  acts_as_commentable

  validate :content_by_type

  def content_by_type
    errors.add(:content, "text required") if (self.content.empty? && self.type_id == 1)
  end




end

app/controllers/chmoods_controller.rb
class ChmoodsController < ApplicationController

  before_filter :authenticate_user!

  def add

    if request.post? && !params.blank?


      #chmood = Chmood.new(data)

      # @chmood = current_user.chmoods.build(user_params)
      @chmood = Chmood.new(user_params)
      @chmood.user_id = current_user.id
      @chmood.created_at = Time.now
      @chmood.updated_at = Time.now

      if @chmood.save
        flash[:notice] = "Woohoo! Your chmood has been created!"
        redirect_to :back # chmoods_add_path
      else
        flash[:error] = "Smth gone wrong...\r\n" # + @chmood.errors.to_a.join("\r\n")
      end

    else
      @user = current_user
      @chmood = Chmood.new(:user_id => @user.id, :colour_id => rand(1..5), :type_id => 1)
    end

  end

  def show

  end


  def comment_add

    @chmood_comment = Comment.build_from(Chmood.find(user_params[:chmood_id]), current_user.id, user_params[:body]);

    respond_to do |format|
      if @chmood_comment.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.js   {}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end


    #if request.xhr?
    #  render :json => @chmood_comment
    #end
  end


  private

  def user_params
    params.require(:chmood).permit(:colour_id, :type_id, :content, :desc, :tags, :image)
  end

  def user_params_comment
    params.require(:comment).permit(:chmood_id, :body, :user_id)
  end

end

app/helpers/chmoods_helper.rb
module ChmoodsHelper


  # adds 3 dots if the text is too long
  def dottize(s, after_length)

    dots = (s.length > after_length) ? ' ...' : ''

    if (s.split(' ').count > 1)
      s.split(" ").each_with_object("") {|x,ob| break ob unless (ob.length + " ".length + x.length <= after_length);ob << (" " + x)}.strip
      s + dots
    else
      s[0..(after_length-1)] + dots
    end
  end


end

app/views/chmoods/_chmoods_list.html.erb
<% chmoods.each do |chmood| %>
  <li class="">
    <div class="chmood-container colour colour-<%= chmood.colour_id %>">
      <% if chmood.image.url(:medium) != '/images/medium/missing.png' %>
          <%= image_tag chmood.image.url(:medium), {style: "width:100%"} %>
      <% else %>
        <div class="chmood-content chmood-text">
            <%= h (chmood.desc.empty?) ? dottize(chmood.content, 20) : dottize(chmood.desc, 20) %>
        </div>
      <% end %>
      <div class="likes" style="padding-left: 2px; padding-right: 2px; border-bottom: 1px solid #AFAEAE; border-top: 1px solid #ececec; padding-bottom: 12px;">
        <%
           c_for = Random.rand(1..100)
           c_against = (100 - c_for)
        %>
        <% if c_for > 0 %>
            <div style="margin-left:2px; box-shadow: 0px 2px 12px rgba(0, 0, 0, 0.48); display: inline-block; background: #31c6a0; border: 2px solid #e1e2e4; border-radius: 8px; width: <%= c_for - 2 %>%; height: 7px"></div>
        <% end %>
        <% if c_against > 0%>
            <div style="box-shadow: 0px 2px 12px rgba(0, 0, 0, 0.48); display: inline-block; background: #f76353; border: 2px solid #e3e4e6; border-radius: 8px; width: <%= c_against - 2 %>%; height: 7px"></div>
        <% end %>
      </div>
      <div class="chmood-info" onclick="window.location.href = $(this).find('.user_link').attr('href'); ">
        <div class="left" style="display: inline-block; overflow: auto">
          <%= image_tag chmood.user.gravatar_url :size => 24  %>
        </div>
        <div style="color: #939495; display: inline-block; padding-left: 2px; overflow: hidden">
          <div style="font-weight: 600"><%= link_to chmood.user.email, user_show_path(chmood.user), {:class => 'user_link'}  %></div>
          <div style=""><%= distance_of_time_in_words_to_now(chmood.updated_at) %> ago</div>
        </div>
        <div class="clearfix"></div>

      </div>
      <div class="chmood-comments">
        <% chmood.comment_threads.each do |c| %>
            <div class="chmood-comment" style="font-size: 11px; padding-bottom: 6px">
              <div class="left" style="float: left; display: inline-block; width: 14%; overflow: hidden; ">
                <%= image_tag c.user.gravatar_url :size => 24  %>
              </div>
              <div class="" style="color: #939495; display: inline-block; padding-left: 2px; width: 84%; margin-top: -4px; overflow: hidden">
                <div style="font-weight: 600"><%= link_to c.user.email, user_show_path(c.user) %></div>
                <div style=""><%= dottize(c.body, 250) %></div>
              </div>
              <div class="clearfix"></div>
            </div>
        <% end %>

        <div class="chmood-comment" style="font-size: 11px; padding-bottom: 6px">
          <div class="left" style="float: left; display: inline-block; width: 14%; overflow: hidden; ">
            <%= image_tag current_user.gravatar_url :size => 24  %>
          </div>
          <div class="" style="display: inline-block; padding-left: 2px; width: 84%; margin-top: -4px;">
            <div style="color: #939495; font-size: 11px">
              <form name="comment-new-form" action="/comments" method="post">
                  <!--<input type="hidden" id="comment-new-user-id" name="comment_user_id" value="<%= current_user.id %>"/>-->
                  <textarea id="comment-new-<%= chmood.id %>" name="comment_body" class="text optional form-control" style="margin-top: 3px" cols="26" rows="3" placeholder="Add your super-duper comment"></textarea>
                  <!--<div class="form-actions" style="margin-bottom: 6px">-->
                    <!--<input class="btn btn-primary" name="commit-new-submit" type="submit" value="Comment">-->
                  <!--</div>-->
              </form>

            </div>
          </div>
          <div class="clearfix"></div>
        </div>

      </div>
    </div>

  </li>
<% end %>

app/views/chmoods/_form_new_chmood.html.erb
<%= simple_form_for chmood, :url => :chmoods_add, html: {class: 'form-horizontal', :multipart => true } do |f| %>

    <% if chmood.errors.any? %>
        <div id="error_explanation">
          <strong><%= pluralize(chmood.errors.count, "reason") %> why we can't yet save your chmood:</strong>

          <ul>
            <% chmood.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-md-8">
        <div id="chmood_colour" class="btn-group" data-toggle="buttons">
          <label class="btn btn-primary colour-tag-1 active">
            <input type="radio" name="options" id="chmood_colour_option1" value="1">Comedy
          </label>
          <label class="btn btn-primary colour-tag-2">
            <input type="radio" name="options" id="chmood_colour_option2" value="2">Inspired
          </label>
          <label class="btn btn-primary colour-tag-3">
            <input type="radio" name="options" id="chmood_colour_option3" value="3">Discover
          </label>
          <label class="btn btn-primary colour-tag-4">
            <input type="radio" name="options" id="chmood_colour_option4" value="4">Creatives
          </label>
          <label class="btn btn-primary colour-tag-5">
            <input type="radio" name="options" id="chmood_colour_option5" value="5">Memories
          </label>

        </div>
      </div>
      <div class="col-md-4">
        <div id="chmood_type" class="btn-group pull-right" data-toggle="buttons">
          <label class="btn btn-primary active">
            <input type="radio" name="options" id="chmood_type_option1">Text
          </label>
          <label class="btn btn-primary">
            <input type="radio" name="options" id="chmood_type_option2">Image
          </label>
        </div>
      </div>

    </div>





    <%= f.input_field :colour_id, :as => :hidden, :id => 'chmood_colour_id', :value => 1 %>
    <%= f.input_field :type_id, :as => :hidden, :id => 'chmood_type_id', :value => 1 %>
    <%= f.input_field :content, :as => :text, :id => 'chmood_content', :title => "Write some content here!", :placeholder => 'So, what do you want to post?' %>
    <%= f.input_field :desc, :as => :text, :id => 'chmood_desc', :title => "Write some description here!", :placeholder => 'Add some description (not required)' %>
    <%= f.file_field :image, {:id => 'chmood_image'} %>
    <div class="form-actions">
      <%= f.button :submit, {class: 'btn-primary' } %>
    </div>
<% end %>


<script type="application/javascript">

    $('#chmood_image').toggle();

    $(document).ready(function() {

        //toogle chmood creation mode, whether user wants to add imaged or texted post
        $('#chmood_type').click(function () {
            //console.log($(this).button().active());
            $('#chmood_content').toggle();
            //$('#chmood_desc').toggle();
            $('#chmood_image').toggle();

            var $type = $('#chmood_type_id');

            if (parseInt($type.val()) > 1) {
                $type.val(1)
            }else {
                $type.val(2)
            }


        });

        $('#chmood_colour').click(function () {
            setTimeout(changeColourInput); // needs to be executed after Bootstrap's events
        });

        function changeColourInput() {
            $('#chmood_colour .btn').each(function(i, btn){
                if($(btn).hasClass('active') ){
                    var colour_id = $(btn).find('input[type="radio"]').val();
                    $('#chmood_colour_id').val(colour_id);
                }
            });
        }
    });


</script>

app/views/chmoods/add.html.erb
<div class="row" id="new_chmood_container">
  <div class="col-sm-3"></div>
  <div class="col-sm-6" style="margin-left: 18px">
    <button type="button" class="close" aria-hidden="true" onclick="$('#new_chmood_container').hide();" style="padding-top: 26px">&times;</button>

    <h1>Add new Chmood</h1>

    <%= render :partial => 'chmoods/form_new_chmood', :locals => { :chmood => @chmood } %>

    <script type="text/javascript">
//        (function ($){
            <!--<% unless (@chmood.errors.any?)%>-->
//            $('#new_chmood_container').hide();
            <!--<% end %>-->
//        })(jQuery);
    </script>

  </div>
  <div class="col-sm-4"></div>

</div>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div id="main" role="main">
      <ul id="grid" class="grid effect-6">
        <!--<li id="chmood-new" class="chmood-new" onclick="$('#new_chmood_container').toggle(); $('#chmood_content').focus();">-->
          <!--<div class="chmood chmood-text">-->
            <!--<span class="icon-plus">+</span><br/><br/>Add New One-->
          <!--</div>-->
        <!--</li>-->
        <!-- These are our grid blocks -->
        <%= render :partial => 'chmoods/chmoods_list', :locals => { :chmoods => current_user.chmoods } %>
      </ul>
    </div>
  </div>
  <div class="col-sm-3"></div>
</div>





<!-- Once the page is loaded, initalize the plug-in. -->
<script type="text/javascript">
//    $(document).ready(function () {
//
//
//        var handler = $('#tiles li');
//
//        var $tiles = $('#tiles'),
//                $handler = $('li', $tiles),
//                $main = $('#main'),
//                $window = $(window),
//                $document = $(document),
//                options = {
//                    // Prepare layout options.
//                    autoResize: true, // This will auto-update the layout when the browser window is resized.
//                    container: $('#main'), // Optional, used for some extra CSS styling
//                    offset: 24, // Optional, the distance between grid items
//                    outerOffset: 10, // Optional, the distance to the containers border
//                    itemWidth: "30%" // Optional, the width of a grid item
//                    ,flexibleWidth: true
//                    ,align: 'left'
//
//                };
//
//        /**
//         * Reinitializes the wookmark handler after all images have loaded
//         */
//        function applyLayout() {
//
//            $tiles.imagesLoaded(function() {
//                // Destroy the old handler
//                if ($handler.wookmarkInstance) {
//                    $handler.wookmarkInstance.clear();
//                }
//
//                // Create a new layout handler.
//                $handler = $('li', $tiles);
//                $handler.wookmark(options);
//
//
//            });
//
//        }
//
//        // Call the layout function for the first time
//        //applyLayout();
//        $handler.wookmark(options);
//
//
//    });
</script>